services:
  - type: web
    name: pizzacone
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn pizzacone_project.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.12.2
    autoDeploy: true
    disk:
      - name: media
        mountPath: /opt/render/project/src/media
        sizeGB: 1

  - type: pserv
    name: pizzacone-db
    plan: free
    ipAllowList: []
