# Generated by Django 6.0.7 on 2026-07-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(help_text='e.g. "Downtown Farmers Market" or "Oak St. & 5th Ave"', max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, help_text='Optional extra info, e.g. "Look for the red tent!"', max_length=255)),
                ('map_url', models.URLField(blank=True, help_text='Optional link to Google Maps or similar.')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
