# Generated by Django 6.0.7 on 2026-07-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationstop',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo for this stop — event flyer, venue photo, the truck at that spot, etc.', null=True, upload_to='location_stops/'),
        ),
        migrations.AddField(
            model_name='locationstop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Optional — pinpoints the spot on the map (e.g. 39.781721).', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='locationstop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Optional — pinpoints the spot on the map (e.g. -89.650148).', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='locationstop',
            name='map_url',
            field=models.URLField(blank=True, help_text='Optional link to Google Maps or similar (used if no lat/long is set).'),
        ),
    ]
