# Generated by Django 6.0.7 on 2026-07-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_venuerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Used by the site templates to find this text — changing it breaks the link to its spot on the site.",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable name shown here in the dashboard.",
                        max_length=150,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("home", "Home Page"),
                            ("about", "About Page"),
                            ("visit", "Find Us Page"),
                            ("contact", "Contact Info"),
                            ("footer", "Footer"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Plain text — line breaks are preserved, no HTML needed.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Text",
                "verbose_name_plural": "Site Text",
                "ordering": ["section", "label"],
            },
        ),
    ]
