# Generated by Django 6.0.7 on 2026-07-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitetext",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Plain-English note on exactly where this shows up on the site, so it's easy to tell blocks apart.",
                max_length=255,
            ),
        ),
    ]
