"""
Django settings for pizzacone_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass

# SECURITY: Load sensitive values from environment variables
def _is_strong_secret_key(value):
    return bool(value) and len(value) >= 50 and not value.startswith('django-insecure-') and len(set(value)) >= 5


SECRET_KEY = os.environ.get('SECRET_KEY')
if os.environ.get('ENVIRONMENT') == 'production':
    if not _is_strong_secret_key(SECRET_KEY):
        raise ValueError(
            'SECRET_KEY must be set as a strong environment variable in production. '
            'Generate a new secret key with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
        )
else:
    if not _is_strong_secret_key(SECRET_KEY):
        # Development: ignore weak or missing values so local checks stay clean.
        import secrets
        SECRET_KEY = secrets.token_urlsafe(50)

# SECURITY: Debug must be False in production
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# SECURITY: Configure allowed hosts
allowed_hosts = os.environ.get('ALLOWED_HOSTS')
if allowed_hosts:
    ALLOWED_HOSTS = allowed_hosts.split(',')
elif os.environ.get('ENVIRONMENT') == 'production':
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com', 'pizzacone.onrender.com']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # The Pizza Cone Co. apps
    'core',
    'menu',
    'dashboard',
    'sales',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Security: Add rate limiting middleware
    'django_ratelimit.middleware.RatelimitMiddleware',
]

ROOT_URLCONF = 'pizzacone_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pizzacone_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Support both SQLite (development) and PostgreSQL (production/Render)
if ENVIRONMENT == 'production':
    # Production: Use PostgreSQL
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Development: Use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # OWASP recommends minimum 12 characters
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================================
# SECURITY HARDENING - OWASP Top 10
# ============================================================================

# OWASP #1: Broken Access Control
# Session security
SESSION_COOKIE_SECURE = ENVIRONMENT == 'production'  # Only send over HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
SESSION_COOKIE_SAMESITE = 'Strict'  # Prevent CSRF
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# OWASP #2: Cryptographic Failures & #3: Injection
# CSRF Protection
CSRF_COOKIE_SECURE = ENVIRONMENT == 'production'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'
csrf_trusted_origins = os.environ.get('CSRF_TRUSTED_ORIGINS')
if csrf_trusted_origins:
    CSRF_TRUSTED_ORIGINS = csrf_trusted_origins.split(',')
elif ENVIRONMENT == 'production':
    CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com', 'https://pizzacone.onrender.com']
else:
    CSRF_TRUSTED_ORIGINS = ['http://localhost:8000']

# OWASP #4: Insecure Design & #5: Security Misconfiguration
# HTTP Security Headers
SECURE_SSL_REDIRECT = ENVIRONMENT == 'production'
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_BROWSER_XSS_FILTER = True

# CSP directives - use constant to avoid duplication
_CSP_SELF = "'self'"
SECURE_CONTENT_SECURITY_POLICY = {
    'default-src': [_CSP_SELF],
    'script-src': [_CSP_SELF, "'unsafe-inline'"],  # Consider removing unsafe-inline
    'style-src': [_CSP_SELF, "'unsafe-inline'"],
    'img-src': [_CSP_SELF, 'data:', 'https:'],
    'font-src': [_CSP_SELF],
    'connect-src': [_CSP_SELF],
    'frame-ancestors': ["'none'"],
    'base-uri': [_CSP_SELF],
    'form-action': [_CSP_SELF],
}
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking
X_CONTENT_TYPE_OPTIONS = 'nosniff'

# OWASP #6: Vulnerable and Outdated Components
# Keep dependencies updated (see requirements.txt and regular security updates)

# OWASP #7: Identification and Authentication Failures
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour

# Authentication backends for additional security
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# OWASP #8: Software and Data Integrity Failures
# Use signed cookies
SESSION_COOKIE_SAMESITE = 'Strict'
LANGUAGE_COOKIE_SAMESITE = 'Strict'
LANGUAGE_COOKIE_SECURE = ENVIRONMENT == 'production'

# OWASP #9: Logging and Monitoring Failures
# Configure logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'security': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.environ.get('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# OWASP #10: Server-Side Request Forgery (SSRF)
# Restrict allowed hosts and media serving
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Allowed file types for uploads
ALLOWED_FILE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.webp']
MAX_FILE_SIZE = 5 * 1024 * 1024  # 5MB


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user-uploaded menu item photos)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth / staff dashboard login
LOGIN_URL = 'dashboard:login'
LOGIN_REDIRECT_URL = 'dashboard:home'
LOGOUT_REDIRECT_URL = 'core:home'

# The Pizza Cone Co. — business settings
STORE_NAME = 'The Pizza Cone Co.'
STORE_PHONE = '(555) 123-4663'
STORE_ADDRESS = '123 Main Street, Anytown, USA'
STORE_HOURS = 'Mon–Sat: 11am–9pm  |  Sun: 12pm–7pm'
